export enum TypeCatTypeMovement {
    MAINTENANCE = "MANTENIMIENTO",
    LOCAL = "LOCAL",
    VEHICLEMAINTENANCE = "MANTENIMIENTO VEHICULO",
    PAYS = "PAGOS",
    CONTRACTEXTENSION = "EXTENSION DE CONTRATO",
}