export enum TypeCatTypeMovement {
    MAINTENANCE = "MANTENIMIENTO",
    LOCAL = "LOCAL",
    VEHICLEMAINTENANCE = "MANTENIMIENTO VEHICULO",
    PAYS = "PAGOS",
    CONTRACTEXTENSION = "EXTENSION DE CONTRATO",
    VEHICLEPURCHASE = "COMPRA DE VEHICULO",
    REPORT = "REPORTE",
}