export enum TypeCatPaymentMethodAdmin {
  MXN = 'Pesos Mexicanos',
  TRANSFER = 'Transferencia',
  CASH = 'Efectivo',
  CREDIT = 'Credito/Debito',
  USD = 'US$',
  EUR = 'E$',
  CAN = 'CAN',
  GBP = 'GBP',
  CLIP = 'CLIP',
  CUENTA = 'CUENTA',
  GENERIC_CURRENCY = '$',
  PAYPAL = 'PAYPAL',
  ARS = 'AR$',
  MERCADO_PAGO = 'MERCADO PAGO',
  TRANSFERENCIA = 'TRANSFERENCIA',
  PAGO_PENDIENTE = 'PAGO PENDIENTE',
  ZELLE = 'ZELLE',
}
